online_cafe/main_page/urls.py
"""Module with urlpatterns."""

from django.urls import path

from .views import main_page_view

app_name = "main_page"

urlpatterns = [
    path("", main_page_view, name="main-page"),
]

online_cafe/online_cafe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("", include("main_page.urls")),
    path("admin/", admin.site.urls),
    path("orders/", include("orders.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="docs"),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

online_cafe/orders/urls.py
"""Module with urlpatterns."""

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import api, views

app_name = "orders"

routers = DefaultRouter()
routers.register("", api.OrderViewSet)

urlpatterns = [
    path("", views.OrderListView.as_view(), name="orders-list"),
    path("revenue/", views.get_revenue_per_shift, name="orders-revenue"),
    path("new/", views.OrderCreateView.as_view(), name="orders-create"),
    path("<int:pk>/", views.OrderDetailView.as_view(), name="orders-detail"),
    path("<int:pk>/update/", views.OrderUpdateView.as_view(), name="orders-update"),
    path("<int:pk>/delete/", views.OrderDeleteView.as_view(), name="orders-delete"),
    path("api/", include(routers.urls)),
]

online_cafe/main_page/models.py
"""Module with models."""

online_cafe/menu/models.py
"""Module with ORM models."""

from django.db import models


class Dish(models.Model):
    """ORM representation of the table of dishes."""

    name: models.CharField = models.CharField(
        max_length=30, blank=False, null=False, help_text="Название блюда"
    )
    description: models.TextField = models.TextField(
        null=True, blank=True, help_text="Описание блюда"
    )
    price: models.DecimalField = models.DecimalField(
        max_digits=7, decimal_places=2, null=False, help_text="Цена блюда"
    )

    class Meta:
        """Class Meta."""

        verbose_name_plural = "Dishes"

    def __str__(self) -> str:
        """Return the string representation of the model."""
        return f"{self.name} ({self.pk}) - {self.price}"

online_cafe/orders/models.py
"""Module with ORM models."""

from typing import Dict

from django.core.validators import MinValueValidator
from django.db import models
from menu.models import Dish


class Order(models.Model):
    """ORM representation of the table of orders."""

    STATUSES: Dict[str, str] = {
        "done": "готово",
        "paid": "оплачено",
        "pending": "в ожидании",
    }

    table_number: models.IntegerField = models.IntegerField(
        null=False, verbose_name="Номер стола", validators=[MinValueValidator(0)]
    )
    items: models.ManyToManyField = models.ManyToManyField(
        Dish, verbose_name="Список блюд в заказе"
    )
    status: models.CharField = models.CharField(
        choices=STATUSES,
        verbose_name="Статус заказа",
        default="в ожидании",
    )

    class Meta:
        """Meta class."""

        ordering = ["pk"]

    @property
    def total_price(self) -> float:
        """Get total price."""
        return sum(self.items.values_list("price", flat=True))

    def __str__(self) -> str:
        """Return string representation of the model."""
        return f"Заказ #{self.pk} - стол №{self.table_number}"

online_cafe/main_page/views.py
"""Module with views."""

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def main_page_view(request: HttpRequest) -> HttpResponse:
    """View main page."""
    return render(request, "main_page/main-page.html")

online_cafe/menu/views.py
"""Module with views."""

online_cafe/orders/views.py
"""Class with Views."""

from typing import List

from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .models import Order


class OrderCreateView(CreateView):
    """Create view class for Order."""

    model = Order
    fields = "table_number", "items"
    success_url = reverse_lazy("orders:orders-list")
    template_name = "orders/orders-create.html"


class OrderListView(ListView):
    """List view class for Order."""

    template_name = "orders/orders-list.html"
    context_object_name = "orders"

    @classmethod
    def __filter_status(cls, statuses: List[str]):
        """
        Add up the status filters bitwise.

        :param statuses: List of statuses from GET params.
        :return: Q(status=status[0]) | Q(status=status[1]) |...
        """
        result = Q(status=statuses[0])
        for i in range(1, len(statuses)):
            result = result | Q(status=statuses[i])
        return result

    def get_queryset(self):
        """Get a queryset depending on the GET parameters."""
        table_number = self.request.GET.get("table_number")
        statuses = self.request.GET.getlist("status")
        if not statuses and not table_number:
            return Order.objects.prefetch_related("items")
        elif not statuses:
            return Order.objects.prefetch_related("items").filter(
                table_number=table_number
            )
        elif not table_number:
            return Order.objects.prefetch_related("items").filter(
                self.__filter_status(statuses)
            )
        else:
            return Order.objects.prefetch_related("items").filter(
                Q(table_number=table_number) & self.__filter_status(statuses)
            )


class OrderDetailView(DetailView):
    """Detail view class for Order."""

    queryset = Order.objects.prefetch_related("items")
    template_name = "orders/orders-detail.html"
    context_object_name = "order"


class OrderUpdateView(UpdateView):
    """Update view class for Order."""

    model = Order
    fields = ("status", "items")
    template_name = "orders/orders-update.html"

    def get_success_url(self):
        """Return success redirect url."""
        return reverse(
            "orders:orders-detail",
            kwargs={"pk": self.object.pk},
        )


class OrderDeleteView(DeleteView):
    """Delete view class for Order."""

    model = Order
    success_url = reverse_lazy("orders:orders-list")
    template_name = "orders/orders-delete.html"


def get_revenue_per_shift(request: HttpRequest) -> HttpResponse:
    """Get revenue per shift."""
    paid_orders = Order.objects.filter(status="оплачено").all()
    revenue = sum(order.total_price for order in paid_orders)
    context = {"revenue": revenue, "orders": paid_orders}
    return render(request, "orders/orders-revenue.html", context=context)

online_cafe/main_page/templates/main_page/main-page.html
{% extends "base.html" %}

{% block title %}
Главная
{% endblock %}

{% block main_page_module %}
<h1 class="bd-title" id="content">Effective Mobile (Тестовое задание)</h1>
<br>
<h2>Добро пожаловать!</h2>
<p>Привет! Рад видеть вас здесь. Меня зовут Волосников Владимир, и эту страницу я создал, чтобы немного рассказать о себе и своих навыках.</p>
<p>Я увлечён разработкой на Python и работой с Django, Flask и FastAPI. Моя цель — создавать удобные, функциональные и масштабируемые решения, которые действительно работают.</p>
<p>Работать в Effective Mobile для меня — это не просто возможность, а шанс присоединиться к команде профессионалов, которая делает классные продукты. Я уверен, что смогу внести свой вклад в ваши проекты, применяя свои навыки и продолжая расти вместе с вашей командой.</p>
<p>На странице вы найдёте мои контакты и портфолио. Если у вас есть вопросы или предложения — буду рад пообщаться!</p>
<h3>Портфолио</h3>
<p><a href="https://github.com/limOnDev13"><b>github</b>: https://github.com/limOnDev13</a></p>
<h3>Контакты</h3>
<ul>
    <li>
        <b>email</b>: volosnikovvladimir69@gmail.com
    </li>
    <li>
        <b>telegram</b>: @limOnFresh1303
    </li>
    <li>
        <a href="https://www.linkedin.com/in/volosnikovvladimir/"><b>LinkedIn</b>: https://www.linkedin.com/in/volosnikovvladimir/</a>
    </li>
</ul>
{% endblock %}

online_cafe/online_cafe/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel='stylesheet' href="{% static '/css/bootstrap.css' %}">

    <title>
        {% block title %}
            Effective Mobile cafe
        {% endblock %}
    </title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main_page:main-page' %}">Effective Mobile</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'orders:orders-list' %}">Заказы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'orders:orders-create' %}">Создать заказ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'orders:orders-revenue' %}">Выручка</a>
        </li>
        <li>
            <form class="d-flex" method="GET" action="{% url 'orders:orders-list' %}">
                <input class="form-control me-2" type="search" placeholder="Поиск по столам" aria-label="Search" name="table_number">
                <div class="btn-group">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Поиск по статусам
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <div class="form-check">
                              <input class="form-check-input" type="checkbox" name="status" value="в ожидании" id="flexCheckChecked">
                              <label class="form-check-label" for="flexCheckChecked">
                                в ожидании
                              </label>
                            </div>
                        </li>
                        <li>
                            <div class="form-check">
                              <input class="form-check-input" type="checkbox" name="status" value="оплачено" id="flexCheckChecked">
                              <label class="form-check-label" for="flexCheckChecked">
                                оплачено
                              </label>
                            </div>
                        </li>
                        <li>
                            <div class="form-check">
                              <input class="form-check-input" type="checkbox" name="status" value="готово" id="flexCheckChecked">
                              <label class="form-check-label" for="flexCheckChecked">
                                готово
                              </label>
                            </div>
                        </li>
                    </ul>
                </div>
                <button class="btn btn-outline-success" type="submit">Поиск</button>
            </form>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            {% block main_page_module %}
            {% endblock %}
        </div>
        <div class="col-sm-2"></div>
    </div>

    <script src="{% static '/js/bootstrap.js' %}"></script>
    <script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

online_cafe/orders/templates/orders/orders-create.html
{% extends "base.html" %}

{% block title %}
Новый заказ
{% endblock %}

{% block main_page_module %}
<h1 class="bd-title" id="content">Создать новый заказ</h1>
<br>
<form method="POST" action="{% url 'orders:orders-create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Создать</button>
</form>
{% endblock %}

online_cafe/orders/templates/orders/orders-delete.html
{% extends "base.html" %}

{% block title %}
Удалить заказ
{% endblock %}

{% block main_page_module %}
<h1 class="bd-title" id="content">Удалить заказ #{{order.pk}}</h1>
<br>
<form method="POST" action="{% url 'orders:orders-delete' pk=order.pk %}">
    {% csrf_token %}
    <p>Вы хотите удалить заказ?</p>
    {{ form.as_p }}
    <button class="btn btn-danger text-end" type="submit">Удалить</button>
</form>
{% endblock %}

online_cafe/orders/templates/orders/orders-detail.html
{% extends "base.html" %}

{% block title %}
Детали заказа
{% endblock %}

{% block main_page_module %}
<h1 class="bd-title" id="content">Заказ #{{order.pk}}</h1>
<br>
<table class="table table-striped align-middle">
    <tr>
        <td>Номер стола</td>
        <td>{{order.table_number}}</td>
    </tr>
    <tr>
        <td>Блюда</td>
        <td>
            {% for item in order.items.all %}
            <p>{{item}}</p>
            {% endfor %}
        </td>
    </tr>
    <tr>
        <td>Общая стоимость</td>
        <td>{{order.total_price}}</td>
    </tr>
    <tr>
        <td>Статус</td>
        <td><b>{{order.get_status_display}}</b></td>
    </tr>
</table>
<a href="{% url 'orders:orders-update' pk=order.pk %}" class="btn btn-primary text-start">Изменить</a>
<a href="{% url 'orders:orders-delete' pk=order.pk %}" class="btn btn-danger text-end">Удалить</a>
{% endblock %}

online_cafe/orders/templates/orders/orders-list.html
{% extends "base.html" %}

{% block title %}
Список заказов
{% endblock %}

{% block main_page_module %}
<h1 class="bd-title" id="content">Список заказов</h1>
<br>
{% if orders %}
<table class="table table-striped align-middle">
    <thead>
        <tr>
            <td><b>id</b></td>
            <td><b>Номер стола</b></td>
            <td><b>Список блюд</b></td>
            <td><b>Общая цена</b></td>
            <td><b>Статус</b></td>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for order in orders %}
        {% if order.status == "в ожидании" %}
        <tr class="table-light">
        {% elif order.status == "готово" %}
        <tr class="table-success">
        {% elif order.status == "оплачено" %}
        <tr class="table-primary">
        {% endif %}
            <td><a href="{% url 'orders:orders-detail' pk=order.pk%}">{{order.pk}}</a></td>
            <td>{{order.table_number}}</td>
            <td>
                {% for item in order.items.all %}
                <p>{{item}}</p>
                {% endfor %}
            </td>
            <td>{{order.total_price}}</td>
            <td>{{order.get_status_display}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
Пока нет заказов
{% endif %}
{% endblock %}

online_cafe/orders/templates/orders/orders-revenue.html
{% extends "base.html" %}

{% block title %}
Список заказов
{% endblock %}

{% block main_page_module %}
<h1 class="bd-title" id="content">Выручка за смену: {{revenue}}</h1>
<table class="table table-sm">
    <thead>
        <tr>
            <td><b>id</b></td>
            <td><b>Номер стола</b></td>
            <td><b>Общая цена</b></td>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for order in orders %}
        <tr class="table-light">
            <td><a href="{% url 'orders:orders-detail' pk=order.pk%}">{{order.pk}}</a></td>
            <td>{{order.table_number}}</td>
            <td>{{order.total_price}}</td>
        </tr>
        {% endfor %}
        <tr class="table-success">
            <td></td>
            <td></td>
            <td>{{revenue}}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

online_cafe/orders/templates/orders/orders-update.html
{% extends "base.html" %}

{% block title %}
Изменить статус заказа
{% endblock %}

{% block main_page_module %}
<h1 class="bd-title" id="content">Изменить статус заказа</h1>
<br>
<form method="POST" action="{% url 'orders:orders-update' pk=order.pk %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Изменить</button>
</form>
{% endblock %}